[project]
name = "cpp_ros_template"
version = "0.1.0"
description = "Add a short description here"
authors = ["Austin Gregg-Smith <blooop@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
platforms = ["linux-64"]

[tasks]
build = "colcon build"
test =" colcon test"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
