[project]
name = "leetcode_template"
version = "0.1.0"
description = "Add a short description here"
authors = ["Austin Gregg-Smith <blooop@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
platforms = ["linux-64"]

[tasks]
build = "colcon build"
cpp-fmt = { cmd = "clang-format -i leetcode_template/src/*.[hc]pp" }
cpp-fmt-check = { cmd = "clang-format --dry-run --Werror -i src/*.[hc]pp" }
test = {cmd= "colcon test; colcon test-result --all --verbose", depends-on = ["build"]}

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
# C++ build-tools:
cmake = "3.27.6"
clang-tools = ">=15,<16" # clang-format
cxx-compiler = "1.6.0.*"